name: Commitlint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - name: Run commitlint
        uses: opensource-nepal/commitlint@v1
