on:
    pull_request:
        branches: [main]
jobs:
    lints: # fast lints
        name: Lints
        uses: ./.github/workflows/lints.yml
    matlab: # heavy MATLAB checks
        name: MATLAB checks
        needs: lints
        uses: ./.github/workflows/matlab.yml
