on: 
  workflow_dispatch:
permissions:
  contents: read
jobs:
  template_users:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Find Template Users
      uses: maael/template-repository-usage-action@v1.2.0
      with:
        token: ${{ secrets.github_token }}
        heading_level: 3
